# -*- coding: utf-8 -*-
"""buyiPhone.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Aq-9-OzEF2PZ1EHaKR_60qN1vLhu2oKA
"""

import pandas as pd
dfs = pd.read_html('https://www.cht.com.tw/home/apple/iphone/index')
df = dfs[0]
df.head()

# 觀察 df['月繳金額.1']包含‘個月’的訊息
df[df['月繳金額.1'].str.contains('個月',na=False)]

# 增加一欄 month --> df[].str.extract()
df['month'] = df['月繳金額.1'].str.extract('(\d+)個月')
df.head()

# 填滿填滿 month內的數字
df['month'] = df['month'].ffill()
df.head()

# 移除資料為 na的列
df.dropna(inplace=True)
df.head()

# 在df[]過濾包含“個月”的raw
df2 = df[~df['月繳金額.1'].str.contains('個月')]
df2.head()

df2.columns

df2.columns = ['購機優惠價', '機型', '容量', '$599', '$799', '$999', '$1,199', '$1,399',
       '$1,599', '$1,799', '$2,699', 'month']

df2.head()

df3 = pd.wide_to_long(df2, ['$'], i=['購機優惠價', '機型', '容量','month'], j='m_price', suffix='[\d,]+')
df3.head()

df3.reset_index(inplace=True)
df3.head()

df4 = df3[df3['$'] != '-']
df4.head()

#打開 df4檢視裡面的資料型態
df4.info()

#將 moth欄的資料轉換為 int型態
df4['month'] = df4['month'].astype(int)

# 將 m_price內的資料轉為 int型態
df4['m_price'] = df4['m_price'].map(lambda e: int(e.replace(',','')))

# 將 m_price內的資料轉為 int型態
df4['$'] = df4['$'].astype(int)

# 總價計算
df4['total'] = df4['month'] * df4['m_price'] + df4['$']

# 總價/綁訂月數
df4['avg'] = (df4['total'] / df4['month']).astype(int)

# 在綁定期間每月平均需付的金額
df4.sort_values('avg')

