# -*- coding: utf-8 -*-
"""pttMovie.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HSTcQtP4BmoLb6noCYPSwWHB8P1qtdzT
"""

import requests
headers = {'User-Agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15'}
res = requests.get('https://www.ptt.cc/bbs/movie/index.html', headers = headers)
res.encoding = 'utf-8'
#res.text

from bs4 import BeautifulSoup
soup = BeautifulSoup(res.text, 'lxml')
titles = soup.find_all("div", class_="title")
for title in titles:
  if title.a != None:
    print(title.a.string)

import json
res1 = requests.get('https://www.sportslottery.com.tw/zh-tw/game/pre')